services:
  - type: web
    name: melodymind-backend
    env: python
    plan: free
    pythonVersion: 3.11
    buildCommand: pip install --upgrade pip setuptools wheel && pip install -r requirements.txt && npm install
    startCommand: node server.js
