services:
  - type: web
    name: melodymind-backend
    env: python
    pythonVersion: "3.13"
    buildCommand: |
      pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
      npm install
    startCommand: node server.js
    envVars:
      - key: MONGO_URI
        sync: false
