# services:
#   - type: web
#     name: melodymind-backend
#     env: python
#     pythonVersion: "3.13"
#     buildCommand: |
#       pip install --upgrade pip setuptools wheel
#       pip install -r requirements.txt
#       npm install
#     startCommand: node server.js
#     envVars:
#       - key: MONGO_URI
#         sync: false
services:
  - type: web
    name: melodymind-backend
    env: node           # <-- change this from python to node
    plan: free
    buildCommand: |
      # Step 1: Build frontend
      cd melodymind-frontend
      npm install
      npm run build

      # Step 2: Install backend dependencies
      cd ../melodymind-backend
      npm install
    startCommand: node server.js
    envVars:
      - key: MONGO_URI
        sync: false
