
# services:
#   - type: web
#     name: melodymind-backend
#     env: node           # <-- change this from python to node
#     plan: free
#     buildCommand: |
#       # Step 1: Build frontend
#       cd melodymind-frontend
#       npm install
#       npm run build

#       # Step 2: Install backend dependencies
#       cd ../melodymind-backend
#       npm install
#     startCommand: node server.js
#     envVars:
#       - key: MONGO_URI
#         sync: false
services:
  - type: web
    name: melodymind-backend
    env: node
    plan: free
    buildCommand: |
      # Step 1: Build frontend
      cd melodymind-frontend
      npm install
      npm run build

      # Step 2: Install backend dependencies
      cd ../melodymind-backend
      npm install

      # Step 3: Install Python 3 and dependencies
      apt-get update && apt-get install -y python3 python3-pip ffmpeg libsndfile1
      pip3 install -r requirements.txt
    startCommand: node server.js
    envVars:
      - key: MONGO_URI
        sync: false
