services:
  - type: web
    name: melodymind-backend
    env: node
    plan: free
    region: oregon
    branch: master
    buildCommand: npm install && pip install -r requirements.txt
    startCommand: node server.js
    envVars:
      - key: MONGO_URI
        fromDatabase:
          name: melody-mind-db
          key: connection_string
